### ISSUE TITLE
Problem with .service files

### ISSUE THREAD

**Issue by guillaume8375** [bjarneo/Spotipy#1]
Hi,

This app doesn't work.

When I'm launching it, I get the following exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/song", line 70, in <module>
    app()
  File "/usr/local/bin/song", line 7, in app
    spotify = Spotify.Spotify()
  File "/home/guillaume/bin/PythonSpotify/Spotify.py", line 17, in __init__
    dbus.SessionBus().get_object('org.mpris.MediaPlayer2.spotify', '/org/mpris/MediaPlayer2'),
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
```

**Comment by bjarneo** [comment]
Oh, I forgot to mension on the readme that you actually have to start
spotify. Or else the script can't hook into spotify.

Let me know if it still doesn't work.

Anyways thanks for letting me know. I'll add a better response message than an exception.

**Comment by maxdevjs** [comment]
Just as a reminder, is still not on the readme that we actually have to start
spotify :)

**Comment by bjarneo** [comment]
@max-devjs Sir, you are correct. I'll update the readme today :)

**Comment by bjarneo** [comment]
https://github.com/bjarneo/Pytify/commit/1e5b465ef6a5d9fc127c73d77c444b6b24f6f11e
