### ISSUE TITLE
Error if no song has been started yet

### ISSUE THREAD

**Issue by bjarneo** [bjarneo/Spotipy#63]
```bash
➜  ~  pytify
pytify 3.5.2 [https://github.com/bjarneo/Pytify]
Traceback (most recent call last):
  File "/usr/local/bin/pytify", line 11, in <module>
    load_entry_point('pytify==3.5.2', 'console_scripts', 'pytify')()
  File "/usr/local/lib/python3.6/dist-packages/pytify/cli.py", line 85, in main
    App()
  File "/usr/local/lib/python3.6/dist-packages/pytify/cli.py", line 19, in __init__
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/pytify/cli.py", line 61, in run
    self.interaction()
  File "/usr/local/lib/python3.6/dist-packages/pytify/cli.py", line 72, in interaction
    search_input = custom_prompt(self.pytify.get_current_playing())
  File "/usr/local/lib/python3.6/dist-packages/pytify/linux.py", line 32, in get_current_playing
    return self.metadata.get_current_playing()
  File "/usr/local/lib/python3.6/dist-packages/pytify/dbus/metadata.py", line 23, in get_current_playing
    playing['artist'] = value[0]
IndexError: list index out of range
```

**Comment by nerrons** [comment]
Still experiencing this

**Comment by bjarneo** [comment]
Yeah, have to look into it. Will let you know when it is solved :)

**Comment by bharath-123** [comment]
I am not experiencing this now. I am assuming this issue has been solved?

**Comment by bjarneo** [comment]
@bharath-123 I think so. Can't reproduce it
