### ISSUE TITLE
Error when i try to run Pytify

### ISSUE THREAD

**Issue by emaforlin** [bjarneo/Spotipy#74]
Hi everyone.
i'll be quick, when i try to run it returns an `IndexError`.
Here is the output.
`Traceback (most recent call last):
  File "/usr/local/bin/pytify", line 8, in <module>
    sys.exit(main())
  File "/home/emaa/.local/lib/python3.8/site-packages/pytify/cli.py", line 88, in main
    App()
  File "/home/emaa/.local/lib/python3.8/site-packages/pytify/cli.py", line 19, in __init__
    self.run()
  File "/home/emaa/.local/lib/python3.8/site-packages/pytify/cli.py", line 58, in run
    print(self.pytify.get_current_playing())
  File "/home/emaa/.local/lib/python3.8/site-packages/pytify/linux.py", line 32, in get_current_playing
    return self.metadata.get_current_playing()
  File "/home/emaa/.local/lib/python3.8/site-packages/pytify/dbus/metadata.py", line 23, in get_current_playing
    playing['artist'] = value[0]
IndexError: list index out of range`

I've got a project in my mind so i'll be very greatful if you help me to solve this issue.

**Comment by bjarneo** [comment]
Wow, sorry, did not notice this one. Did you get it up and running?
